### ISSUE TITLE
圈X执行脚本报错

### ISSUE THREAD

**Issue by reapple** [whyour/hundun#10]
❗️京东赚赚, 错误!
TypeError: undefined is not an object (evaluating 'data.taskDetailResList.filter')

==============📣系统通知📣==============
京东赚赚
获得京豆：NaN
获得金币：NaN
账号总金币：undefined

**Comment by whyour** [comment]
@reapple 你的token过去成功了吗

**Comment by reapple** [comment]
token获取成功了

**Comment by whyour** [comment]
@reapple 贴下你的日志

**Comment by reapple** [comment]
iOS 12.4 v1.0.16-build429


🔔京东赚赚, 开始!

开始【京东账号1】jd_4d72a马赛克5

❗️京东赚赚, 错误!
TypeError: undefined is not an object (evaluating 'data.taskDetailResList.filter')

==============📣系统通知📣==============
京东赚赚
获得京豆：NaN
获得金币：NaN
账号总金币：undefined

🔔京东赚赚, 结束! 🕛 0.33 秒

**Comment by whyour** [comment]
@reapple 你网络貌似有问题，重新执行一边呢，切个网

**Comment by whyour** [comment]
> iOS 12.4 v1.0.16-build429
> 
> 🔔京东赚赚, 开始!
> 
> 开始【京东账号1】jd_4d72a马赛克5
> 
> ❗️京东赚赚, 错误!
> TypeError: undefined is not an object (evaluating 'data.taskDetailResList.filter')
> 
> ==============📣系统通知📣==============
> 京东赚赚
> 获得京豆：NaN
> 获得金币：NaN
> 账号总金币：undefined
> 
> 🔔京东赚赚, 结束! 🕛 0.33 秒

没问题了吧

**Comment by reapple** [comment]
还是报那个错。看样子是不能读取data.taskDetailResList.filter这里面的数据？

**Comment by whyour** [comment]
@reapple 你请求接口没返回数据，你换网络了吗

**Comment by reapple** [comment]
4G、WiFi、关闭圈x执行脚本，都试了，一样的报错

**Comment by whyour** [comment]
> 4G、WiFi、关闭圈x执行脚本，都试了，一样的报错

编辑脚本， 83行下面 加       $.log(_data)
然后再执行下，看下日志

**Comment by reapple** [comment]
{"code":"3","message":"用户未登陆"}
找到原因了

**Comment by whyour** [comment]
> {"code":"3","message":"用户未登陆"}
> 找到原因了

手动签一次到，删掉box里的token，清除后台，再获取token

**Comment by reapple** [comment]
用的圈x怎么弄，没用过box

**Comment by whyour** [comment]
> 用的圈x怎么弄，没用过box

https://chavyleung.gitbook.io/boxjs/

加上 https://raw.githubusercontent.com/whyour/hundun/master/quanx/whyour.boxjs.json

**Comment by reapple** [comment]
好，我研究研究
