### ISSUE TITLE
京东赚赚报错

### ISSUE THREAD

**Issue by dover** [whyour/hundun#11]
❗️京东赚赚, 错误!
TypeError: Right side of assignment cannot be destructured

**Comment by whyour** [comment]
> ❗️京东赚赚, 错误!
> TypeError: Right side of assignment cannot be destructured

是哪一步报的错，上一步是啥

**Comment by dover** [comment]
> > ❗️京东赚赚, 错误!
> > TypeError: Right side of assignment cannot be destructured
> 
> 是哪一步报的错，上一步是啥

iOS 13.7 NE v1.0.16-build429

Logs:


🔔京东赚赚, 开始!

开始【京东账号1】ddff

请求正常
{"code":"0","data":{"totalNum":"5000","cashExpected":"可提现约0.50元","cashRatio":"10000:1","userRiskStatus":1,"scoreRiskStatus":0,"morePrizeImgUrl":"https://m.360buyimg.com/babel/jfs/t1/146993/21/7584/133003/5f5219d7E7658a603/223680bd1194266c.png","exchangePrizeList":[{"prizeId":1,"prizeNo":1,"refId":"0","prizeName":"京东赚赚红包0.25元","prizeAmount":0.25,"maxNumExchange":1,"label":"1","status":0},{"prizeId":2,"prizeNo":2,"refId":"0","prizeName":"京东赚赚红包2元","prizeAmount":2.0,"maxNumExchange":3,"status":0},{"prizeId":3,"prizeNo":3,"refId":"0","prizeName":"京东赚赚红包5元","prizeAmount":5.0,"maxNumExchange":2,"status":0},{"prizeId":4,"prizeNo":4,"refId":"0","prizeName":"京东赚赚红包10元","prizeAmount":10.0,"maxNumExchange":1,"status":0},{"prizeId":5,"prizeNo":5,"refId":"0","prizeName":"京东赚赚红包50元","prizeAmount":50.0,"maxNumExchange":1,"status":0},{"prizeId":6,"prizeNo":6,"refId":"0","prizeName":"京东赚赚红包100元","prizeAmount":100.0,"maxNumExchange":1,"status":0}]},"message":"请求正常"}

❗️京东赚赚, 错误!
TypeError: Right side of assignment cannot be destructured

🔔京东赚赚, 结束! 🕛 0.416 秒

**Comment by whyour** [comment]
@dover 那个错没啥影响，你更新下应该就好了

**Comment by whyour** [comment]
> > > ❗️京东赚赚, 错误!
> > > TypeError: Right side of assignment cannot be destructured
> > 
> > 
> > 是哪一步报的错，上一步是啥
> 
> iOS 13.7 NE v1.0.16-build429
> 
> Logs:
> 
> 🔔京东赚赚, 开始!
> 
> 开始【京东账号1】ddff
> 
> 请求正常
> {"code":"0","data":{"totalNum":"5000","cashExpected":"可提现约0.50元","cashRatio":"10000:1","userRiskStatus":1,"scoreRiskStatus":0,"morePrizeImgUrl":"[https://m.360buyimg.com/babel/jfs/t1/146993/21/7584/133003/5f5219d7E7658a603/223680bd1194266c.png","exchangePrizeList":[{"prizeId":1,"prizeNo":1,"refId":"0","prizeName":"京东赚赚红包0.25元","prizeAmount":0.25,"maxNumExchange":1,"label":"1","status":0},{"prizeId":2,"prizeNo":2,"refId":"0","prizeName":"京东赚赚红包2元","prizeAmount":2.0,"maxNumExchange":3,"status":0},{"prizeId":3,"prizeNo":3,"refId":"0","prizeName":"京东赚赚红包5元","prizeAmount":5.0,"maxNumExchange":2,"status":0},{"prizeId":4,"prizeNo":4,"refId":"0","prizeName":"京东赚赚红包10元","prizeAmount":10.0,"maxNumExchange":1,"status":0},{"prizeId":5,"prizeNo":5,"refId":"0","prizeName":"京东赚赚红包50元","prizeAmount":50.0,"maxNumExchange":1,"status":0},{"prizeId":6,"prizeNo":6,"refId":"0","prizeName":"京东赚赚红包100元","prizeAmount":100.0,"maxNumExchange":1,"status":0}]},"message":"请求正常"}](https://m.360buyimg.com/babel/jfs/t1/146993/21/7584/133003/5f5219d7E7658a603/223680bd1194266c.png%22,%22exchangePrizeList%22:%5B%7B%22prizeId%22:1,%22prizeNo%22:1,%22refId%22:%220%22,%22prizeName%22:%22%E4%BA%AC%E4%B8%9C%E8%B5%9A%E8%B5%9A%E7%BA%A2%E5%8C%850.25%E5%85%83%22,%22prizeAmount%22:0.25,%22maxNumExchange%22:1,%22label%22:%221%22,%22status%22:0%7D,%7B%22prizeId%22:2,%22prizeNo%22:2,%22refId%22:%220%22,%22prizeName%22:%22%E4%BA%AC%E4%B8%9C%E8%B5%9A%E8%B5%9A%E7%BA%A2%E5%8C%852%E5%85%83%22,%22prizeAmount%22:2.0,%22maxNumExchange%22:3,%22status%22:0%7D,%7B%22prizeId%22:3,%22prizeNo%22:3,%22refId%22:%220%22,%22prizeName%22:%22%E4%BA%AC%E4%B8%9C%E8%B5%9A%E8%B5%9A%E7%BA%A2%E5%8C%855%E5%85%83%22,%22prizeAmount%22:5.0,%22maxNumExchange%22:2,%22status%22:0%7D,%7B%22prizeId%22:4,%22prizeNo%22:4,%22refId%22:%220%22,%22prizeName%22:%22%E4%BA%AC%E4%B8%9C%E8%B5%9A%E8%B5%9A%E7%BA%A2%E5%8C%8510%E5%85%83%22,%22prizeAmount%22:10.0,%22maxNumExchange%22:1,%22status%22:0%7D,%7B%22prizeId%22:5,%22prizeNo%22:5,%22refId%22:%220%22,%22prizeName%22:%22%E4%BA%AC%E4%B8%9C%E8%B5%9A%E8%B5%9A%E7%BA%A2%E5%8C%8550%E5%85%83%22,%22prizeAmount%22:50.0,%22maxNumExchange%22:1,%22status%22:0%7D,%7B%22prizeId%22:6,%22prizeNo%22:6,%22refId%22:%220%22,%22prizeName%22:%22%E4%BA%AC%E4%B8%9C%E8%B5%9A%E8%B5%9A%E7%BA%A2%E5%8C%85100%E5%85%83%22,%22prizeAmount%22:100.0,%22maxNumExchange%22:1,%22status%22:0%7D%5D%7D,%22message%22:%22%E8%AF%B7%E6%B1%82%E6%AD%A3%E5%B8%B8%22%7D)
> 
> ❗️京东赚赚, 错误!
> TypeError: Right side of assignment cannot be destructured
> 
> 🔔京东赚赚, 结束! 🕛 0.416 秒

你没在box里面设置要换的红包吧
