### ISSUE TITLE
有没有京喜农场和饿了么领水果

### ISSUE THREAD

**Issue by a1564471347** [whyour/hundun#15]
脚本

**Comment by whyour** [comment]
@a1564471347 没有

**Comment by whyour** [comment]
> 脚本

https://raw.githubusercontent.com/whyour/hundun/master/quanx/jx_nc.js
你的京喜农场

**Comment by noelff** [comment]
为什么下了助力码提交？

**Comment by whyour** [comment]
@noelff 那不是我的api，要加作者会加
