### ISSUE TITLE
京喜农场多账号执行存在缺陷

### ISSUE THREAD

**Issue by zczwjh** [whyour/hundun#16]
京喜农场在多账号执行是，如果其中一个账号出错（比如，没有种植），则整个脚本将停止，正确的逻辑应该是只跳出该账号的脚本，接着执行下一个账号的脚本才对。

**Comment by whyour** [comment]
> 京喜农场在多账号执行是，如果其中一个账号出错（比如，没有种植），则整个脚本将停止，正确的逻辑应该是只跳出该账号的脚本，接着执行下一个账号的脚本才对。

你说的没问题，但是一个账号有问题，改下还是得跑，所以优化不是很大，更新了，基本可以满足你的逻辑了
另外可以种植app专属种子了
