### ISSUE TITLE
京东赚赚token获取成功，运行失败

### ISSUE THREAD

**Issue by Nergrove** [whyour/hundun#18]
token写入成功，但是运行签到脚本报错。
日志如下：

用户未登陆

用户未登陆

用户未登陆

用户未登陆

❗️京东赚赚, 错误!
TypeError: undefined is not an object (evaluating 'data.taskDetailResList.filter')

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by whyour** [comment]
@Nergrove 你可以去box清下token试试

**Comment by Nergrove** [comment]
> @Nergrove 你可以去box清下token试试
可以了，谢谢
