### ISSUE TITLE
京喜农场多账号出错

### ISSUE THREAD

**Issue by popeshaka** [whyour/hundun#21]
如题，单账号没问题，单多账号就会报错

**Comment by whyour** [comment]
@popeshaka 报什么错

**Comment by popeshaka** [comment]
> @popeshaka 报什么错

运行第一个账号后，报错信息如下：

获取随机助力码200
助力：has expired 
❗️京喜农场, 错误!
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /scripts/jx_nc.js:51:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

然后脚本就终止了，不继续运行第二个账号了。
单个账号运行时没问题的

**Comment by popeshaka** [comment]
环境是群辉docker

**Comment by whyour** [comment]
@popeshaka 50行打印下  $.tokens[i]

**Comment by fjcqv** [comment]
32行 $.tokens = [$.getdata('jxnc_token1') || '{}', $.getdata('jxnc_token2') || '{}'];
改成 $.tokens = [$.getdata('jxnc_token1') || '{}', $.getdata('jxnc_token2') || '{}','{}','{}','{}','{}'];
数组长度定死了的错误而已，多加几个就行

**Comment by popeshaka** [comment]
> 32行 $.tokens = [$.getdata('jxnc_token1') || '{}', $.getdata('jxnc_token2') || '{}'];
> 改成 $.tokens = [$.getdata('jxnc_token1') || '{}', $.getdata('jxnc_token2') || '{}','{}','{}','{}','{}'];
> 数组长度定死了的错误而已，多加几个就行

多谢，亲测有效

**Comment by whyour** [comment]
@popeshaka 嗯，上次也有人报这个错了，我兼容下

**Comment by whyour** [comment]
@popeshaka 已修复
