### ISSUE TITLE
喜马拉雅极速版

### ISSUE THREAD

**Issue by Jankinsu** [whyour/hundun#23]
敢问大佬，我想使用action跑Python脚本，可是util包不能用pip install 部署，怎么解决哇

**Comment by whyour** [comment]
> 敢问大佬，我想使用action跑Python脚本，可是util包不能用pip install 部署，怎么解决哇

直接把项目下的util拷贝过去就行了

**Comment by Jankinsu** [comment]
哦哦哦，我蠢了谢谢大佬
