### ISSUE TITLE
惊喜农场多账号又出现问题了

### ISSUE THREAD

**Issue by popeshaka** [whyour/hundun#25]
报错代码如下
TypeError: Cannot read property 'limit' of undefined
    at getMessage (/scripts/jx_nc.js:99:51)
    at /scripts/jx_nc.js:64:7
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by FanchangWang** [comment]
这个是完成任务后查询任务列表，helpTask 没了导致的，这是用于计算预计几天的，我复制了一份代码暂时把计算天数的给删掉了

**Comment by whyour** [comment]
@FanchangWang 多谢，我一会修改下

**Comment by whyour** [comment]
@FanchangWang @popeshaka 已修复
