### ISSUE TITLE
京喜农场token问题

### ISSUE THREAD

**Issue by zglzw** [whyour/hundun#26]
大佬请问京喜农场token应该如何获得？看了脚本头部说明还是不知道如何操作

**Comment by Dellear** [comment]
> 大佬请问京喜农场token应该如何获得？看了脚本头部说明还是不知道如何操作

同疑惑 @whyour

**Comment by FanchangWang** [comment]
需要有代理拦截 url ，url 的参数上有这 3 个字段。quanx 之类的可以之类有脚本拦截，安卓也可以用手机版的代理软件获取

**Comment by zglzw** [comment]
那请问ios使用Thor或者pc上使用Fiddler是不是都能获取到？具体应该如何操作？谢谢

**Comment by FanchangWang** [comment]
iOS 不了解，fiddler 是可以的

**Comment by whyour** [comment]
@Dellear @zglzw 添加 https://raw.githubusercontent.com/whyour/hundun/master/quanx/jx_nc.cookie.js 文件头部的重写，手动完成一个任务就行

**Comment by jaysherlock** [comment]
> iOS 不了解，fiddler 是可以的

请问安卓有什么app可以用啊

**Comment by zglzw** [comment]
好的谢谢大佬，我去试试

**Comment by whyour** [comment]
> 那请问ios使用Thor或者pc上使用Fiddler是不是都能获取到？具体应该如何操作？谢谢

自己抓，也是抓做任务的包，看记录里中 url 包含  `farm/dotask`  的，取url中的这三个字段 `farm_jstoken`  `phoneid` `timestamp` 合成一个 `{ 'farm_jstoken': xxx, phoneid: xxx, timestamp: xxx }` 的值，看不懂就用 cookie文件开头的重写抓吧

**Comment by zglzw** [comment]
> > 那请问ios使用Thor或者pc上使用Fiddler是不是都能获取到？具体应该如何操作？谢谢
> 
> 自己抓，也是抓做任务的包，看记录里中 url 包含 `farm/dotask` 的，取url中的这三个字段 `farm_jstoken` `phoneid` `timestamp` 合成一个 `{ 'farm_jstoken': xxx, phoneid: xxx, timestamp: xxx }` 的值，看不懂就用 cookie文件开头的重写抓吧

感谢大佬，已经使用Thor成功抓取

**Comment by yezhizhzao** [comment]
> @Dellear @zglzw 添加 https://raw.githubusercontent.com/whyour/hundun/master/quanx/jx_nc.cookie.js 文件头部的重写，手动完成一个任务就行

![image](https://user-images.githubusercontent.com/63447582/105530689-13103580-5d23-11eb-971d-c35d419f2529.jpeg)

**Comment by HenryTSZ** [comment]
请问有人设置成功 财富岛 的 token 了吗? 

是不是必须提现成功才能获取到 token, 别的请求获取的都是错误的?

农场获取的 token 是不是不能在财富岛用?
