### ISSUE TITLE
Below JS engines remain active for too long

### ISSUE THREAD

**Issue by EchoChan314** [whyour/hundun#28]
[QTXJSVirtualMachine]: Below JS engines remain active for too long, please check whether the $done function is called correctly. This message might be a false alarm:

   * <08C1B8E6-F9E6-4303-9E80-300C7F7AC605> created at: "2021年1月29日 星期五 中国标准时间 21:10:00", lived for: 6000 seconds, source: https://raw.githubusercontent.com/whyour/hundun/master/quanx/jd_zjd_tuan.js
  
我看代码里面有调用$done()，但QX还是提示执行时间过长。

**Comment by whyour** [comment]
> This message might be a false alarm:

This message might be a false alarm
获取可能是 api 调用是不是超时了，但是感觉怎么也不会1个多小时吧

**Comment by whyour** [comment]
> [QTXJSVirtualMachine]: Below JS engines remain active for too long, please check whether the $done function is called correctly. This message might be a false alarm:
> 
> * <08C1B8E6-F9E6-4303-9E80-300C7F7AC605> created at: "2021年1月29日 星期五 中国标准时间 21:10:00", lived for: 6000 seconds, source: https://raw.githubusercontent.com/whyour/hundun/master/quanx/jd_zjd_tuan.js
> 
> 我看代码里面有调用$done()，但QX还是提示执行时间过长。

可以再观察下，我刚改了下，猜测可能是获取助力码报错，但是未resolve
