### ISSUE TITLE
youth可以部署云函数吗？为啥我的部署上后运行老出错，本地运行没问题

### ISSUE THREAD

**Issue by shishixiu** [whyour/hundun#30]
youth可以部署云函数吗？为啥我的部署上后运行老出错，本地运行没问题

**Comment by whyour** [comment]
@shishixiu 贴下错误日志

**Comment by shishixiu** [comment]
> @shishixiu 贴下错误日志

![image](https://user-images.githubusercontent.com/47021717/107917915-b01d6180-6fa3-11eb-9e7b-36570c5e4e7c.png)
![image](https://user-images.githubusercontent.com/47021717/107918009-dc38e280-6fa3-11eb-840f-483dddaa8b48.png)

**Comment by whyour** [comment]
> > @shishixiu 贴下错误日志
> 
> ![image](https://user-images.githubusercontent.com/47021717/107917915-b01d6180-6fa3-11eb-9e7b-36570c5e4e7c.png)
> ![image](https://user-images.githubusercontent.com/47021717/107918009-dc38e280-6fa3-11eb-840f-483dddaa8b48.png)

默认生成的 index.py 改成下面的 把youth.py 和 util.py 都拷贝过去

```python
# -*- coding: utf8 -*-
import json
import run from 'youth'
def main_handler(event, context):
    run()
```

**Comment by shishixiu** [comment]
大佬 还是失败
![image](https://user-images.githubusercontent.com/47021717/107977783-a96c0a00-6ff6-11eb-8059-b0ada1aec249.png)
![image](https://user-images.githubusercontent.com/47021717/107977805-b5f06280-6ff6-11eb-8d91-1de1f6106275.png)

**Comment by whyour** [comment]
> 大佬 还是失败
> ![image](https://user-images.githubusercontent.com/47021717/107977783-a96c0a00-6ff6-11eb-8059-b0ada1aec249.png)
> ![image](https://user-images.githubusercontent.com/47021717/107977805-b5f06280-6ff6-11eb-8d91-1de1f6106275.png)

import run from youth
改成
from youth import run

**Comment by shishixiu** [comment]
> > 大佬 还是失败
> > ![image](https://user-images.githubusercontent.com/47021717/107977783-a96c0a00-6ff6-11eb-8059-b0ada1aec249.png)
> > ![image](https://user-images.githubusercontent.com/47021717/107977805-b5f06280-6ff6-11eb-8d91-1de1f6106275.png)
> 
> ```python
> import run from youth
> 改成
> from youth import run
> ```

谢谢大佬 成功了

**Comment by 50733364** [comment]
老哥们 可以给个 HEADER 格式吗？    例如  "Cookie":"xxx" "cookie_id":"xx""uid":"xax"   我一直没搞懂 是不是这样。
