### ISSUE TITLE
京喜工厂开团或者加入别的团经常失败

### ISSUE THREAD

**Issue by EchoChan314** [whyour/hundun#32]
就是凑不到5个人组团，不管是自己开的团还是参加别人的团。
不知道有没有办法让组团更容易成立？

**Comment by whyour** [comment]
> 就是凑不到5个人组团，不管是自己开的团还是参加别人的团。
> 不知道有没有办法让组团更容易成立？

这个得记录团里的人数，我有时间可以重构成团接口试试
大体逻辑就是 先从库里随机取几个，然后让这几个成团后， 再从库里随机取几个，无限重复
