### ISSUE TITLE
京东挖现金

### ISSUE THREAD

**Issue by 50733364** [whyour/hundun#34]
作者你好 你有空研究下挖现金这个活动吗？
京东搜索挖现金就可以进去查看活动，貌似给的还行。

**Comment by whyour** [comment]
> 作者你好 你有空研究下挖现金这个活动吗？
> 京东搜索挖现金就可以进去查看活动，貌似给的还行。

这个活动需要的助力人数太多了吧，这也成不了

**Comment by 50733364** [comment]
是的。 主要我今天抓包试了下。 无论如何都助力不了 但助力机会都消耗了。 因为tg（lxk ）有助力池 所以我想问下大佬你能不能写一下。  而且这个貌似时长还挺久的。
