### ISSUE TITLE
xmly_speed.py

### ISSUE THREAD

**Issue by johnny115** [whyour/hundun#37]
util.py send 不起作用?

ac不推送是什么回事 已设置好
secrets 里面已经添加好 但BARK SCKEY 企业微信都不推送
查日志已经检测到但就是不推送 哪里出错了

    BARK: ***
    SCKEY: ***
    TG_BOT_TOKEN: 
    TG_USER_ID: 
    DD_BOT_ACCESS_TOKEN: 
    DD_BOT_SECRET: 
    QYWX_APP: ***

BARK 推送打开
Server酱 推送打开
企业微信应用 推送打开

但最后没有任何推送 哪里没有设置好?

**Comment by whyour** [comment]
> util.py send 不起作用?
> 
> ac不推送是什么回事 已设置好
> secrets 里面已经添加好 但BARK SCKEY 企业微信都不推送
> 查日志已经检测到但就是不推送 哪里出错了
> 
> ```
> BARK: ***
> SCKEY: ***
> TG_BOT_TOKEN: 
> TG_USER_ID: 
> DD_BOT_ACCESS_TOKEN: 
> DD_BOT_SECRET: 
> QYWX_APP: ***
> ```
> 
> BARK 推送打开
> Server酱 推送打开
> 企业微信应用 推送打开
> 
> 但最后没有任何推送 哪里没有设置好?

有没有错误信息

**Comment by johnny115** [comment]
build里面有打印消息 但外面没有收到任何消息.

【 打印账号信息】
当前剩余:0
今日获得:0
累计获得:0

############################################################

不知道哪里出错了 而且哪里可以看debug?

**Comment by ilaotan** [comment]
> build里面有打印消息 但外面没有收到任何消息.
> 
> 【 打印账号信息】
> 当前剩余:0
> 今日获得:0
> 累计获得:0
> 
> ############################################################
> 
> 不知道哪里出错了 而且哪里可以看debug?

notify_time = 23                            # 通知时间,24小时制,默认19
你配置的多少

**Comment by ilaotan** [comment]
notify_time = 23                            # 通知时间,24小时制,默认19

你配置的多少

**Comment by johnny115** [comment]
这个我日夜晚11点 都没有收到通知啊.... 用AC跑的 是一直都没有收过通知....其他正常收到通知的

不想当厨子的老谭 ***@***.***> 于2021年3月15日周一 下午4:11写道：

**Comment by ilaotan** [comment]
你既然这么问了,肯定ac里正常跑过 贴ac的运行日志吧,

**Comment by johnny115** [comment]
运行日志 是 build 里面的东西吗 ?
如下

Run python3 xmly_speed.py
  python3 xmly_speed.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.10/x64
    XMLY_SPEED_COOKIE: ***
  
    AUTO_TAKE_OUT: 
    BARK: ***
    SCKEY: ***
    TG_BOT_TOKEN: 
    TG_USER_ID: 
    DD_BOT_ACCESS_TOKEN: 
    DD_BOT_SECRET: 

BARK 推送打开
Server酱 推送打开

喜马拉雅极速版 (https://github.com/Zero-S1/xmly_speed/blob/master/xmly_speed.md ) ,欢迎打赏¯\(°_o)/¯

当前时间戳: 1615795394
北京时间: 2021-03-15 16:03:14.179424


>>>>>>>【账号开始1】

iPhone&03DA6C93-56AB-4AC2-BB33-71FB13DA00EC&1.0.12

【用户信息】
{'msg': '0', 'ret': 0, 'vipViewInfo': {'expireDate': 1646150399000, 'expireDays': 351, 'vipStatus': 2}, 'isVip': True, 'mobileSmallLogo': 'http://imagev2.xmcdn.com/group61/M0A/7C/F4/wKgMZl0wBcvgM4XpAABed_RytoA536.jpg!op_type=5&upload_type=header&device_type=ios&name=mobile_small', 'uid': 31905681, 'vipResourceInfo': {'buttonContent': 'http://fdfs.xmcdn.com/group78/M07/8A/74/wKgO4F5QotyjKx9NAAB5HGuiU_8785.png', 'url': 'https://m.ximalaya.com/business-vip-presale-web/speed/product/page/1581646752678?orderSource=speed_Other_MyPage_VipCard'}, 'mobileLargeLogo': 'http://imagev2.xmcdn.com/group61/M0A/7C/F4/wKgMZl0wBcvgM4XpAABed_RytoA536.jpg!op_type=5&upload_type=header&device_type=ios&name=mobile_x_large', 'nickname': 'Bing_i5', 'mobileMiddleLogo': 'http://imagev2.xmcdn.com/group61/M0A/7C/F4/wKgMZl0wBcvgM4XpAABed_RytoA536.jpg!op_type=5&upload_type=header&device_type=ios&name=web_x_large'}

【刷时长1】
上传本地收听时长1: 963分钟
{"msg":"0","ret":0,"uid":31905681,"signature":"dd60cc7baf432b7837560b63d30320ff","currentTimeMillis":1615795395000,"activtyId":"listenAward","nativeListenTime":57794,"showBall":false}

【刷时长2】
上传本地收听时长2: 963分钟
{"code":0,"msg":"","data":{"canBeCollectedCoins":0,"needReminder":false,"aboutToExpireCoins":0,"timeRequiredNextStage":107,"nextStageReward":50}}

【新手任务】

【阅读】

【bubble】
暂无有效气泡

【连续签到】
{'checkId': None, 'historyDays': 9, 'continuousDays': 9, 'isTickedToday': True, 'thatDay': 9, 'broken': False, 'canMakeUp': False, 'newUser': False, 'receivedToday': True}
连续签到9/30天
True

【答题】
{"code":0,"msg":"","data":{"stamina":0,"remainingTimes":0,"helpLimitFlag":false}}
时间未到

【收听获得抽卡机会】
今日已达上限

 【领取万能卡】
今日已满

【抽卡】
抽卡机会:  [847560]
检查手牌，卡牌兑金币
万能卡:  [1837271, 1837342]

  【首页、宝箱奖励及翻倍】
宝箱奖励:  {'msg': '无法领取，今天领取额度已满', 'ret': 3}
首页奖励:  {'msg': '无法领取，时间没到', 'ret': 3}

【 打印账号信息】
当前剩余: 
今日获得: 
累计获得: 

############################################################

**Comment by johnny115** [comment]
if int(_notify_time.split()[0]) == notify_time and int(_notify_time.split()[1]) < 5:

难道这个话有问题吗?

**Comment by johnny115** [comment]
终于有错误日志了 看看

bark服务启动
Traceback (most recent call last):
  File "xmly_speed.py", line 1085, in <module>
    run()
  File "xmly_speed.py", line 1082, in run
    send(title=title, content=message)
  File "/home/runner/work/210118/210118/util.py", line 268, in send
    bark(title=title, content=content)
  File "/home/runner/work/210118/210118/util.py", line 85, in bark
    response = requests.get(url).json()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
Error: Process completed with exit code 1.

**Comment by whyour** [comment]
> 终于有错误日志了 看看
> 
> bark服务启动
> Traceback (most recent call last):
> File "xmly_speed.py", line 1085, in
> run()
> File "xmly_speed.py", line 1082, in run
> send(title=title, content=message)
> File "/home/runner/work/210118/210118/util.py", line 268, in send
> bark(title=title, content=content)
> File "/home/runner/work/210118/210118/util.py", line 85, in bark
> response = requests.get(url).json()
> File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/models.py", line 900, in json
> return complexjson.loads(self.text, **kwargs)
> File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/**init**.py", line 348, in loads
> return _default_decoder.decode(s)
> File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/json/decoder.py", line 340, in decode
> raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
> Error: Process completed with exit code 1.

你bark参数咋写的

**Comment by johnny115** [comment]
def bark(title, content):
    print("\n")
    if not BARK:
        print("bark服务的bark_token未设置!!\n取消推送")
        return
    print("bark服务启动")
    url = None
    if BARK.startswith('http'):
      url = f"""{BARK}/{title}/{content}"""
    else:
      url = f"""https://api.day.app/{BARK}/{title}/{content}"""
    response = requests.get(url).json()
    if response['code'] == 200:
        print('推送成功！')
    else:
        print('推送失败！')


def send(title, content):
    """
    使用 bark, telegram bot, dingding bot, serverJ 发送手机推送
    :param title:
    :param content:
    :return:
    """
    for i in notify_mode:
        if i == 'bark':
            if BARK:
                bark(title=title, content=content)
            else:
                print('未启用 bark')
            continue

**Comment by whyour** [comment]
> def bark(title, content):
> print("\n")
> if not BARK:
> print("bark服务的bark_token未设置!!\n取消推送")
> return
> print("bark服务启动")
> url = None
> if BARK.startswith('http'):
> url = f"""{BARK}/{title}/{content}"""
> else:
> url = f"""[https://api.day.app/{BARK}/{title}/{content}](https://api.day.app/%7BBARK%7D/%7Btitle%7D/%7Bcontent%7D)"""
> response = requests.get(url).json()
> if response['code'] == 200:
> print('推送成功！')
> else:
> print('推送失败！')
> 
> def send(title, content):
> """
> 使用 bark, telegram bot, dingding bot, serverJ 发送手机推送
> :param title:
> :param content:
> :return:
> """
> for i in notify_mode:
> if i == 'bark':
> if BARK:
> bark(title=title, content=content)
> else:
> print('未启用 bark')
> continue

 你不是 配了  BARK  这个变量吗，这个是什么开头的
