### ISSUE TITLE
老大

### ISSUE THREAD

**Issue by qaz88q11** [whyour/hundun#38]
大佬能不能添加个步步宝的py脚本

**Comment by whyour** [comment]
> 大佬能不能添加个步步宝的py脚本

步步宝提现好提现吗，现在需要50才能提现，周期还挺长，这个如果稳定的话，我有时间写下
也可以推荐其他稳定的

**Comment by qaz88q11** [comment]
> > 大佬能不能添加个步步宝的py脚本
> 
> 步步宝提现好提现吗，现在需要50才能提现，周期还挺长，这个如果稳定的话，我有时间写下
> 也可以推荐其他稳定的
现在可以每日体现0.3没有限制，这个很不错

**Comment by qaz88q11** [comment]
每日可以提现0.3元，毕竟羊毛也是毛

**Comment by ilaotan** [comment]
有js脚本啊

**Comment by qaz88q11** [comment]
> 有js脚本啊

知道 但是想要个py脚本，来放我的py容器运行

**Comment by whyour** [comment]
> 每日可以提现0.3元，毕竟羊毛也是毛

ios现在0.3提不了啊，你先50提一次吧
