### ISSUE TITLE
京喜农场, 错误!

### ISSUE THREAD

**Issue by suppergit** [whyour/hundun#39]
京喜农场执行报错，log如下：

❗️京喜农场, 错误!
TypeError: Cannot read property '1' of null
    at /jd/scripts/jx_nc.js:113:77
    at /jd/scripts/jx_nc.js:335:4880
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

❗️京喜农场, 错误!
TypeError: Cannot read property '1' of null
    at /jd/scripts/jx_nc.js:113:77
    at /jd/scripts/jx_nc.js:335:4880
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by whyour** [comment]
> 京喜农场执行报错，log如下：
> 
> ❗️京喜农场, 错误!
> TypeError: Cannot read property '1' of null
> at /jd/scripts/jx_nc.js:113:77
> at /jd/scripts/jx_nc.js:335:4880
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 
> ❗️京喜农场, 错误!
> TypeError: Cannot read property '1' of null
> at /jd/scripts/jx_nc.js:113:77
> at /jd/scripts/jx_nc.js:335:4880
> at processTicksAndRejections (internal/process/task_queues.js:93:5)

能复现吗，最近貌似数据库扛不住请求，后期可能需要修改

**Comment by suppergit** [comment]
> > 京喜农场执行报错，log如下：
> > ❗️京喜农场, 错误!
> > TypeError: Cannot read property '1' of null
> > at /jd/scripts/jx_nc.js:113:77
> > at /jd/scripts/jx_nc.js:335:4880
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> > ❗️京喜农场, 错误!
> > TypeError: Cannot read property '1' of null
> > at /jd/scripts/jx_nc.js:113:77
> > at /jd/scripts/jx_nc.js:335:4880
> > at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 
> 能复现吗，最近貌似数据库扛不住请求，后期可能需要修改

可以。12号之后的log都是这样的报错。

**Comment by banjuer** [comment]
我也一样..
