### ISSUE TITLE
大佬，你的仓库更新失败

### ISSUE THREAD

**Issue by cjh19831115** [whyour/hundun#44]
Mon Apr 12 2021 23:02:37 GMT+0800 (中国标准时间)
whyour本地仓库不存在,从gayhub拉取ing...
/usr/local/bin/diy: line 35: local: can only be used in a function
fatal: repository 'whyour_hundun' does not exist
whyour本地仓库拉取失败,请检查!

执行结束...

**Comment by qirenzhidao** [comment]
一样，不知道怎么拉取，一直在试，都不行

**Comment by qirenzhidao** [comment]
开始执行...

Mon Apr 19 2021 10:23:26 GMT+0800 (中国标准时间)
本地仓库不存在,从远程拉取ing...
fatal: destination path 'whyour_hundun' already exists and is not an empty directory.
whyour本地仓库拉取失败,请检查!


执行结束...

**Comment by whyour** [comment]
> Mon Apr 12 2021 23:02:37 GMT+0800 (中国标准时间)
> whyour本地仓库不存在,从gayhub拉取ing...
> /usr/local/bin/diy: line 35: local: can only be used in a function
> fatal: repository 'whyour_hundun' does not exist
> whyour本地仓库拉取失败,请检查!
> 
> 执行结束...

最新版的应该好了，提bug要去qinglong项目提，这里的我都没注意
https://github.com/whyour/qinglong
