### ISSUE TITLE
面板添加COOKIE的一个小bug

### ISSUE THREAD

**Issue by qirenzhidao** [whyour/hundun#45]
事情是这样的。我总共2个CK，其中1个CK失效了，于是我在面板单独编辑更新了那个失效的CK，禁用再重新启用CK。状态什么都是正常的，但是脚本执行的时候，这个CK却不执行。 
我把失效的CK删除后，再单独添加这个CK，依然不行。
不断测试，我的解决方法是，
把所有的CK都删除，再把所有的CK按照换行的方式添加一次，才可以。（跟第一遍添加CK的方式一样，也就是说不能单独添加CK）
不知道我说明白了没

**Comment by whyour** [comment]
> 事情是这样的。我总共2个CK，其中1个CK失效了，于是我在面板单独编辑更新了那个失效的CK，禁用再重新启用CK。状态什么都是正常的，但是脚本执行的时候，这个CK却不执行。
> 我把失效的CK删除后，再单独添加这个CK，依然不行。
> 不断测试，我的解决方法是，
> 把所有的CK都删除，再把所有的CK按照换行的方式添加一次，才可以。（跟第一遍添加CK的方式一样，也就是说不能单独添加CK）
> 不知道我说明白了没

说明白了，但是你这提bug的位置不对 https://github.com/whyour/qinglong
这个问题等下次遇到，我远程看看
