### ISSUE TITLE
❗️狂欢城互助码, 错误!

### ISSUE THREAD

**Issue by MisterGlasses** [whyour/hundun#8]
大佬你好，818脚本现在提示如下
❗️狂欢城互助码, 错误!
SyntaxError: JSON Parse error: Unexpected identifier "object"

**Comment by whyour** [comment]
> 大佬你好，818脚本现在提示如下
> ❗️狂欢城互助码, 错误!
> SyntaxError: JSON Parse error: Unexpected identifier "object"

已修复

**Comment by MisterGlasses** [comment]
> > 大佬你好，818脚本现在提示如下
> > ❗️狂欢城互助码, 错误!
> > SyntaxError: JSON Parse error: Unexpected identifier "object"
> 
> 已修复
还是出错

❗️狂欢城互助码, 错误!
ReferenceError: Can't find variable: _resp

❗️狂欢城互助码, 错误!
ReferenceError: Can't find variable: _resp

**Comment by whyour** [comment]
@MisterGlasses 提交了，你再更新试试

**Comment by MisterGlasses** [comment]
> @MisterGlasses 提交了，你再更新试试

这次好了 但是有个不影响使用的小问题 不知道老哥你发现没有 多账号通知有点问题如下

开始【京东账号1】MisterGlasses


==============📣系统通知📣==============
狂欢城互助码
MisterGlasses：此助力码已存在！

开始【京东账号2】jd_7b22bbfe1e7e5


==============📣系统通知📣==============
狂欢城互助码
MisterGlasses：此助力码已存在！
jd_7b22bbfe1e7e5：此助力码已存在！
jd_7b22bbfe1e7e5：此助力码已存在！

**Comment by whyour** [comment]
@MisterGlasses 哈哈，是有问题，更新了下，你试试，我没有多账号

**Comment by MisterGlasses** [comment]
> @MisterGlasses 哈哈，是有问题，更新了下，你试试，我没有多账号

开始【京东账号1】MisterGlasses


开始【京东账号2】jd_7b22bbfe1e7e5


==============📣系统通知📣==============
狂欢城互助码
MisterGlasses：此助力码已存在！
jd_7b22bbfe1e7e5：此助力码已存在！
jd_7b22bbfe1e7e5：此助力码已存在！

**Comment by whyour** [comment]
@MisterGlasses 通知逻辑改了下，有时间可以再试试😂

**Comment by MisterGlasses** [comment]
似乎好了
