### ISSUE TITLE
京东转转

### ISSUE THREAD

**Issue by noelff** [whyour/hundun#9]

**Comment by noelff** [comment]
微信咋搜索不到小程序，微信版本过低吗？

**Comment by noelff** [comment]
微信版本7.0.7

**Comment by whyour** [comment]
> 微信版本7.0.7

不是吧，我的是 7.0.18， 就是这个
![image](https://user-images.githubusercontent.com/22700758/99933460-183e1c00-2d96-11eb-89bb-cc2b518657cc.png)

**Comment by noelff** [comment]
谢谢大佬，写成京东转转了，别字没有搜索到，换赚就好了！

**Comment by whyour** [comment]
@noelff 哈哈，我也写错了，换一下😂
